#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

# Colors: default, black, red, green, yellow, blue, magenta, cyan, white
[secondary_prompt]
  template = '❯❯ '
  foreground = 'green'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    foreground = 'darkGray'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = [
      '{{ if or (.Staging.Changed) (gt .Working.Modified 0) }}lightYellow{{end}}'
    ]
    # nf-fa-code_branch - \uF126
    # nf-fa-code_commit - \uF172
    # nf-fa-tag - \uF02B
    templates = [
      ' {{ if and .Detached (eq .Ref "(detached)") }} {{ substr 0 8 .Commit.Sha }}{{ else if .Detached }} {{ .Ref }}{{ else }} {{ .Ref }}{{ end }}',
      '{{ if gt .Behind 0 }} <cyan>⇣{{ .Behind }}</>{{end}}',
      '{{ if gt .Ahead 0 }}{{ if eq .Behind 0}} {{end}}<cyan>⇡{{ .Ahead }}</>{{end}}',
      '{{ if gt .StashCount 0 }} *{{ .StashCount }}{{end}}',
      # TODO: VCS_STATUS_ACTION (in red)
      '{{ if .Merge }} <red>merge</>{{ end }}',
      '{{ if .Rebase }} <red>rebase</>{{ end }}',
      '{{ if .CherryPick }} <red>cherry</>{{ end }}',
      '{{ if .Revert }} <red>cherry</>{{ end }}',
      '{{ if gt .Working.Unmerged 0 }} <red>~{{ .Working.Unmerged }}</>{{end}}',
      '{{ if .Staging.Changed }} +{{ add .Staging.Added .Staging.Deleted .Staging.Modified }}{{end}}',
      '{{ if gt (add .Working.Modified .Working.Deleted) 0 }} !{{ add .Working.Modified .Working.Deleted }}{{end}}',
      '{{ if gt .Working.Untracked 0 }} ?{{ .Working.Untracked }}{{end}}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  # nf-fa-python - \uED1B
  [[blocks.segments]]
    foreground = 'green'
    background = 'transparent'
    type = 'python'
    style = 'plain'
    templates = [
      '  {{ if .Error }}{{ .Error }}{{ else }} {{ .Full }} {{ if .Venv }}({{ .Venv }}){{ end }}{{ end }}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'context'
      foler_name_fallback = false

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'roundrock'
      threshold = 5000

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }}{{ end }}'
    foreground = 'transparent'
    background = 'blue'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}red{{end}}',
      '{{if eq .Code 0}}green{{end}}',
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
