## App-specific tweaks
source = ~/.config/hypr/apps/1password.conf
#source = ~/.local/share/omarchy/default/hypr/apps/bitwarden.conf
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/freecad.conf
source = ~/.config/hypr/apps/hyprshot.conf
#source = ~/.local/share/omarchy/default/hypr/apps/jetbrains.conf
#source = ~/.local/share/omarchy/default/hypr/apps/localsend.conf
source = ~/.config/hypr/apps/pip.conf
source = ~/.config/hypr/apps/qemu.conf
#source = ~/.local/share/omarchy/default/hypr/apps/retroarch.conf
#source = ~/.local/share/omarchy/default/hypr/apps/steam.conf
#source = ~/.local/share/omarchy/default/hypr/apps/geforce.conf
#source = ~/.local/share/omarchy/default/hypr/apps/moonlight.conf
source = ~/.config/hypr/apps/system.conf
#source = ~/.local/share/omarchy/default/hypr/apps/telegram.conf
source = ~/.config/hypr/apps/terminals.conf
source = ~/.config/hypr/apps/walker.conf
#source = ~/.local/share/omarchy/default/hypr/apps/webcam-overlay.conf
