theme {
  color_scheme = /home/rlovelett/.config/hypr/qt6-dracula.conf
  icon_theme = Colloid-Dracula-Dark
  style = Fusion
  font_fixed = MesloLGSDZ Nerd Font Mono
  font_fixed_size = 12
  font = MesloLGSDZ Nerd Font Mono
  font_size = 12
}
