# FreeCAD window rules
windowrule = float on, size 1000 700, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Welcome)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Preferences)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(About FreeCAD)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Addon manager)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(.*Properties.*)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Select.*)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Save.*)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Open.*)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Export.*)$
windowrule = float on, match:class ^(org\.freecad\.FreeCAD)$, match:title ^(Import.*)$
windowrule = center on, match:class ^(org\.freecad\.FreeCAD)$, match:float 1

