windowrule = tag -default-opacity, match:class qemu
windowrule = opacity 1 1, match:class qemu
windowrule = workspace 9 silent, fullscreen on, match:class ^(xfreerdp)$
windowrule = workspace 10 silent, fullscreen on, match:class ^(looking-glass-client)$
