# Set programs that you use
$terminal = ghostty
$fileManager = nautilus --new-window
$menu = walker
$browser = zen-browser
$passwordManager = 1password

# Application launchers
bindd = SUPER, return,        Open terminal,               exec, $terminal -e tmux new-session -A -s default -n default
bindd = SUPER SHIFT, return,  Open terminal (new session), exec, $terminal -e tmux new-session
bindd = SUPER SHIFT, F,       Open file manager,           exec, $fileManager
bindd = SUPER, B,             Open browser,                exec, $browser
bindd = SUPER, slash,         Open password manager,       exec, $passwordManager
bindd = SUPER, N,             Toggle notifications,        exec, swaync-client -t
bindd = SUPER SHIFT, N,       Toggle do not disturb,       exec, swaync-client -d

# Menus
bindd = SUPER, SPACE, Launch apps, exec, $menu --width 644 --maxheight 300 --minheight 300
bindd = SUPER CTRL, E, Emoji picker, exec, $menu --width 644 --maxheight 300 --minheight 300 -m symbols
bindd = SUPER CTRL, S, Snippets, exec, $menu --width 644 --maxheight 300 --minheight 300 -m snippets
bindd = SUPER, K, Show key bindings, exec, hyprland-keybindings

# Notifications
bindd = SUPER, D,             Dismiss last notification,          exec, makoctl dismiss
bindd = SUPER SHIFT, D,       Dismiss all notifications,          exec, makoctl dismiss --all
#bindd = SUPER CTRL, D,       Toggle silencing notifications,     exec, omarchy-toggle-notification-silencing
bindd = SUPER ALT, D,         Invoke last notification,           exec, makoctl invoke
bindd = SUPER SHIFT ALT, D,   Restore last notification,          exec, makoctl restore

# Toggles
#bindd = SUPER CTRL, I, Toggle locking on idle, exec, omarchy-toggle-idle
#bindd = SUPER CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight

# Captures
bindd = , PRINT, Screenshot (region), exec, hyprshot -m region
bindd = SHIFT, PRINT, Screenshot (window),  exec, hyprshot -m window
bindd = CTRL, PRINT, Screenshot (output),  exec, hyprshot -m output
#bindd = ALT, PRINT, Screenrecording, exec, omarchy-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, hyprland-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, hyprland-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, hyprland-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, hyprland-launch-tui btop

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER, ESCAPE, Lock screen, exec, hyprlock
bindd = SUPER SHIFT, ESCAPE, Suspend, exec, systemctl suspend
bindd = SUPER CTRL, ESCAPE, Reboot, exec, systemctl reboot
bindd = SUPER SHIFT CTRL, ESCAPE, Shut down, exec, systemctl poweroff
bindd = SUPER ALT, ESCAPE, Log out, exec, uwsm stop
